services:
  container1:
    image: container1
    container_name: container1
    ports: 
      - "6000:6000"
    volumes:
      - ./:/app/files
    networks:
      - containernetwork
  container2:
    image: container2
    container_name: container2
    ports: 
      - "8081:8081"
    volumes:
      - ./:/app/files
    networks:
      - containernetwork
networks:
  containernetwork:
    driver: bridge