# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: shared-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /Krishna_PV_dir

# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ""
  # volumeName: shared-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/cloudsummer23/container1/k8cn1:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: krishna-volume
              mountPath: /Krishna_PV_dir
      volumes:
        - name: krishna-volume
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer


