#Source: https://www.youtube.com/watch?v=VACqLwGn5IM and https://cloud.google.com/build/docs/build-push-docker-image#:~:text=Build%20and%20push%20a%20Docker%20image%20with%20Cloud,config%20file%20...%206%20View%20build%20details%20
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloudsummer23/container2/k8cn2:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloudsummer23/container2/k8cn2:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'assignmentkrishnak8', '--zone', 'us-central1-a']
  - name: 'gcr.io/cloud-builders/kubectl'
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a','CLOUDSDK_CONTAINER_CLUSTER=assignmentkrishnak8']
    args: ['apply', '-f', 'Krishna.yaml']

